
test: rpi-node-test
	./rpi-node-test

py-test: 
	test.py

reset:
	gpio write 0 1
	gpio mode 0 out
	gpio write 0 0
	gpio write 0 1
	gpio mode 0 in

detect: reset-i2c
	gpio write 2 1
	gpio mode 2 out
	i2cdetect -y 1
	gpio mode 2 in

reset-i2c:
	rmmod i2c_dev
	rmmod i2c_bcm2708
	sleep 1
	modprobe i2c_bcm2708
	modprobe i2c_dev
	sleep 1

CXXFLAGS=-Wall -L/usr/local/lib -lwiringPi
